// 扫描 src/ 下所有笔记，生成 VitePress 侧边栏与顶部导航
// 产物：.vitepress/sidebar.generated.mts（生成物不提交，dev/build 前自动再生）
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve(import.meta.dir, '..')
const SRC = path.join(ROOT, 'src')

// 与 config.mts 的 srcExclude 对齐：这些目录不进站点
const EXCLUDED_DIRS = new Set([
  'node_modules',
  'dist',
  'build',
  'coverage',
  'target',
  '__pycache__',
  '.venv',
  'venv',
  'skills',
])

// 目录显示名映射（未命中的目录用「去数字前缀的原名」）
const NAME_MAP: Record<string, string> = {
  'artificial-intelligence': '人工智能',
  'computer-science': '计算机科学',
  deploy: '部署与运维',
  english: '英语',
  front: '前端',
  mathematics: '数学',
  'programming-languages': '编程语言',
  server: '服务端',
  doc: '文档',
  projects: '项目实战',
  core: '核心',
  general: '通用',
  frame: '框架',
  db: '数据库',
}

interface Item {
  text: string
  link?: string
  collapsed?: boolean
  items?: Item[]
}

const stripPrefix = (s: string) => s.replace(/^\d+[.\-_ ]*/, '')
const displayName = (name: string) => NAME_MAP[name] ?? stripPrefix(name)

const natural = (a: string, b: string) => a.localeCompare(b, 'zh', { numeric: true })

// 去掉 .md 扩展名、保留原大小写的站内绝对路径（VitePress 自动补 .html）
const toLink = (file: string) =>
  '/' + path.relative(SRC, file).replaceAll('\\', '/').replace(/\.md$/i, '')

function fileTitle(file: string): string {
  const m = readFileSync(file, 'utf-8').match(/^#\s+(.+?)\s*$/m)
  return m ? m[1].trim() : stripPrefix(path.basename(file, '.md'))
}

function readmeLink(dir: string): string | undefined {
  const readme = path.join(dir, 'readme.md')
  return existsSync(readme) ? toLink(readme) : undefined
}

function firstLink(items: Item[]): string | undefined {
  for (const it of items) {
    if (it.link) return it.link
    if (it.items) {
      const found = firstLink(it.items)
      if (found) return found
    }
  }
  return undefined
}

function walk(dir: string): Item[] {
  const entries = readdirSync(dir, { withFileTypes: true })
  const names = entries.map((e) => e.name).sort(natural)
  const items: Item[] = []
  for (const name of names) {
    if (EXCLUDED_DIRS.has(name) || name.startsWith('.')) continue
    const full = path.join(dir, name)
    const entry = entries.find((e) => e.name === name)!
    if (entry.isDirectory()) {
      const children = walk(full)
      if (!children.length) {
        // 目录里只有 readme：保留为单个可点项，避免整组丢失
        const readme = readmeLink(full)
        if (readme) items.push({ text: displayName(name), link: readme })
        continue
      }
      items.push({
        text: displayName(name),
        link: readmeLink(full),
        collapsed: true,
        items: children,
      })
    } else if (/\.md$/i.test(name) && !/^readme\.md$/i.test(name)) {
      // src/index.md 是站点首页，不进侧边栏
      if (path.relative(SRC, full) === 'index.md') continue
      items.push({ text: fileTitle(full), link: toLink(full) })
    }
  }
  return items
}

const topDirs = readdirSync(SRC, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !EXCLUDED_DIRS.has(e.name) && !e.name.startsWith('.'))
  .map((e) => e.name)
  .sort(natural)

const groups = topDirs.map((name) => {
  const full = path.join(SRC, name)
  const items = walk(full)
  return {
    name,
    text: displayName(name),
    items,
    // 分组入口：readme 优先，否则第一篇笔记
    link: readmeLink(full) ?? firstLink(items),
  }
})

const nav = groups.map(({ text, link }) => ({ text, link }))

// 按顶层目录分段展示；'/' 兜底（首页外散页可见全部分组）
const sidebar: Record<string, Item[]> = {
  '/': groups.map(({ text, link, items }) => ({ text, link, collapsed: true, items })),
}
for (const g of groups) sidebar[`/${g.name}/`] = g.items

const out =
  '// @generated by .vitepress/gen-sidebar.ts — DO NOT EDIT\n' +
  '// 重新生成：bun run gen:sidebar\n\n' +
  `export const nav = ${JSON.stringify(nav, null, 2)}\n\n` +
  `export const sidebar = ${JSON.stringify(sidebar, null, 2)}\n`

writeFileSync(path.join(ROOT, '.vitepress', 'sidebar.generated.mts'), out)

const pageCount = JSON.stringify(sidebar).match(/"link"/g)?.length ?? 0
console.log(`✓ sidebar.generated.mts：${groups.length} 个顶层分类，约 ${pageCount} 个页面链接`)
